baseURL = 'https://swhl.github.io/AI-Competition-Collections/'
languageCode = 'en-us'
title = 'AI Competition Collections'

theme = "hugo-theme-relearn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH", "SEARCHPAGE"]

[module]
  [module.hugoVersion]
    min = "0.95.0"

[params]
  additionalContentLanguage = [ "en", "zh" ]
  collapsibleMenu = false

[mediaTypes]
  [mediaTypes."text/javascript"]
    suffixes = ["js"]

[outputFormats]
  [outputFormats.PRINT]
    name= "PRINT"
    baseName = "index.print"
    isHTML = true
    mediaType = 'text/html'
    permalinkable = false
    noUgly = true

  [outputFormats.SEARCH]
    name= "SEARCH"
    baseName = "index.search"
    isPlainText = true
    mediaType = 'text/javascript'
    permalinkable = false
    noUgly = true

  [outputFormats.SERCHPAGE]
    name= "SEARCHPAGE"
    baseName = "search"
    isHTML = true
    mediaType = 'text/html'
    permalinkable = false
    noUgly = true
